"""Alterações nos modelos

Revision ID: 312748ae1b9e
Revises: 
Create Date: 2025-10-15 19:21:06.975194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312748ae1b9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despacho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data_despacho', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', 'CONCLUIDO', 'CANCELADO', name='estadodespachoenum'), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('anexo_nome', sa.String(length=255), nullable=True),
    sa.Column('anexo_tipo', sa.String(length=50), nullable=True),
    sa.Column('anexo_dados', sa.LargeBinary(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licenca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('PENDENTE', 'APROVADA', 'REJEITADA', 'CONCLUIDA', 'CANCELADA', name='estadolicencaenum'), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('anexo_nome', sa.String(length=255), nullable=True),
    sa.Column('anexo_tipo', sa.String(length=50), nullable=True),
    sa.Column('anexo_dados', sa.LargeBinary(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipolicenca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidato_edicao', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'candidato', ['candidatoId'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidato_edicao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('licenca')
    op.drop_table('despacho')
    # ### end Alembic commands ###
