"""Alterações nos modelos

Revision ID: ee5bcd04bcb8
Revises: 312748ae1b9e
Create Date: 2025-10-15 19:45:50.380503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5bcd04bcb8'
down_revision = '312748ae1b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('despacho_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'despacho', ['despacho_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licenca', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('despacho_id')

    # ### end Alembic commands ###
